apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: speakin
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: server-message_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        envFrom:  
        - configMapRef:
            name: message-service-config
        - secretRef:
            name: message-service-secrets
        volumeMounts:
        - name: message-service-code
          mountPath: /app
      volumes:
      - name: message-service-code
        hostPath:
          path: "/run/desktop/mnt/host/d/hamraz hakeem/desktop/speakin/server/message_service"
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: speakin
spec:
  selector:
    app: message-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP