apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: speakin
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: server-session_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        envFrom:  
        - configMapRef:
            name: session-service-config
        - secretRef:
            name: session-service-secrets
        volumeMounts:
        - name: session-service-code
          mountPath: /app
      volumes:
      - name: session-service-code
        hostPath:
          path: "/run/desktop/mnt/host/d/hamraz hakeem/desktop/speakin/server/session_service"
          type: Directory 

---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: speakin
spec:
  selector:
    app: session-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP