apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: speakin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: user-service-code
          mountPath: /app
      volumes:
      - name: user-service-code
        hostPath:
          path: "/run/desktop/mnt/host/d/hamraz hakeem/desktop/speakin/server/user_service"
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: speakin
spec:
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
  type: ClusterIP