apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-worker
  namespace: speakin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-worker
  template:
    metadata:
      labels:
        app: user-service-worker
    spec:
      containers:
      - name: user-service-worker
        image: server-user_service:latest
        imagePullPolicy: Never
        command: ["celery", "-A", "user_service", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets