apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speakin-ingress
  namespace: speakin
  annotations:
    # AWS ALB Annotations
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:609400231968:certificate/9e3d8a8f-2dcb-4669-b3c3-b2a8bad8bed3
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    
    # Timeouts
    alb.ingress.kubernetes.io/idle-timeout: "3600"
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    
    # Security
    alb.ingress.kubernetes.io/security-groups: sg-0e26e2a406df9ddeb

    # Health Check Annotations for API Gateway
    alb.ingress.kubernetes.io/healthcheck-path: /api/health/
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'

spec:
  ingressClassName: alb
  rules:
  - host: backend.speakin.hamrazhakeem.tech
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      - pathType: Prefix
        path: /ws
        backend:
          service:
            name: message-service
            port:
              number: 8003