apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: speakin
data:
  grafana.ini: |
    [server]
    root_url = https://backend.speakin.hamrazhakeem.site/grafana
    serve_from_sub_path = true

    [security]
    admin_user = admin
    admin_password = $__file{/etc/grafana/admin/admin-password}

    [auth]
    disable_login_form = false

    [users]
    allow_sign_up = false
    auto_assign_org_role = Viewer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: speakin
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy