apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "False"
  ALLOWED_HOSTS: "message-service,backend.speakin.hamrazhakeem.site"
  CORS_ALLOWED_ORIGINS: "https://speakin.hamrazhakeem.site"

  # Database settings
  DB_HOST: "speakin-db.czq066m88qo6.eu-north-1.rds.amazonaws.com"  # From RDS endpoint
  DB_PORT: "5432"

  # Service URLs
  USER_SERVICE_URL: "http://user-service:8000/"

  # Redis settings
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"