apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: speakin
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - json:
              expressions:
                output: log
                stream: stream
                timestamp: time
          - timestamp:
              source: timestamp
              format: RFC3339Nano
          - labels:
              stream:
          - output:
              source: output

      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
        pipeline_stages:
          - docker: {}
          - json:
              expressions:
                output: log
                stream: stream
                attrs: attrs
          - labels:
              stream:
          - output:
              source: output