apiVersion: v1
kind: ConfigMap
metadata:
  name: session-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "False"
  ALLOWED_HOSTS: "session-service,backend.speakin.hamrazhakeem.tech"

  # Database settings
  DB_PORT: "5432"

  # Daily.co settings
  DAILY_API_ROOM_URL: "https://api.daily.co/v1/rooms"
  DAILY_API_MEETING_TOKEN_URL: "https://api.daily.co/v1/meeting-tokens"
  BASE_VIDEO_CALL_URL: "https://speakin.daily.co/"

  # Service URLs
  USER_SERVICE_URL: "http://user-service:8000/"
  PAYMENT_SERVICE_URL: "http://payment-service:8001/"

  # Celery settings
  CELERY_BROKER_URL: "redis://redis:6379/3"
  CELERY_RESULT_BACKEND: "redis://redis:6379/3"
  CELERY_TIMEZONE: "UTC"
  CELERY_BROKER_CONNECTION_RETRY: "True"

  # User service grpc host
  USER_SERVICE_GRPC_HOST: "user-service"

  # Payment service grpc host
  PAYMENT_SERVICE_GRPC_HOST: "payment-service"