apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: speakin
data:
  # General settings
  DEBUG: "True"
  ALLOWED_HOSTS: "api-gateway,localhost,127.0.0.1"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
  
  # Service URLs
  USER_SERVICE_URL: "http://user-service:8000/"
  PAYMENT_SERVICE_URL: "http://payment-service:8001/"
  SESSION_SERVICE_URL: "http://session-service:8002/"
  MESSAGE_SERVICE_URL: "http://message-service:8003/"