apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "True"
  ALLOWED_HOSTS: "message-service,localhost"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"

  # Database settings
  DB_HOST: "message-db" 
  DB_PORT: "5435"

  # Service URLs
  USER_SERVICE_URL: "http://user-service:8000/"

  # Redis settings
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"