apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "True"
  ALLOWED_HOSTS: "host.docker.internal,127.0.0.1,localhost"
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"

  # Database settings
  DB_HOST: "message_service_db"
  DB_PORT: "5432"

  # Service URLs
  USER_SERVICE_URL: "http://host.docker.internal:8000/"

  # Redis settings
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"