apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "True"
  ALLOWED_HOSTS: "payment-service,localhost,api-gateway"

  # Database settings
  DB_HOST: "payment-db"
  DB_PORT: "5433"

  # Frontend URL
  FRONTEND_DOMAIN: "http://localhost:5173"

  # User service grpc host
  USER_SERVICE_GRPC_HOST: "user-service.speakin.svc.cluster.local"