apiVersion: v1
kind: ConfigMap
metadata:
  name: session-service-config
  namespace: speakin
data:
  # General settings
  DEBUG: "True"
  ALLOWED_HOSTS: "host.docker.internal,127.0.0.1,localhost"

  # Database settings
  DB_HOST: "session_service_db"
  DB_PORT: "5432"

  # Daily.co settings
  DAILY_API_ROOM_URL: "https://api.daily.co/v1/rooms"
  DAILY_API_MEETING_TOKEN_URL: "https://api.daily.co/v1/meeting-tokens"
  BASE_VIDEO_CALL_URL: "https://speakin.daily.co/"

  # Service URLs
  USER_SERVICE_URL: "http://host.docker.internal:8000/"
  PAYMENT_SERVICE_URL: "http://host.docker.internal:8001/"

  # Celery settings
  CELERY_BROKER_URL: "redis://redis:6379/3"
  CELERY_RESULT_BACKEND: "redis://redis:6379/3"
  CELERY_TIMEZONE: "UTC"
  CELERY_BROKER_CONNECTION_RETRY: "True"