apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: session-service-worker-hpa
  namespace: speakin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: session-service-worker
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70