apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: speakin
spec:
  replicas: 2
  selector:
    matchLabels:    
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: hamrazhakeem/speakin-message-service:latest
        ports:
        - containerPort: 8003
        envFrom:  
        - configMapRef:
            name: message-service-config
        - secretRef:
            name: message-service-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: speakin
spec:
  selector:
    app: message-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP