apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: speakin
spec:
  replicas: 2
  selector:
    matchLabels:    
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: hamrazhakeem/speakin-payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http  
        - containerPort: 50052
          name: grpc
        envFrom:
        - configMapRef:
            name: payment-service-config
        - secretRef:
            name: payment-service-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: speakin
spec:
  selector:
    app: payment-service
  ports:
    - port: 8001
      targetPort: 8001
      name: http
    - port: 50052
      targetPort: 50052
      name: grpc
  type: ClusterIP