apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service-worker
  namespace: speakin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-service-worker
  template:
    metadata:
      labels:
        app: session-service-worker
    spec:
      containers:
      - name: session-service-worker
        image: hamrazhakeem/speakin-session-service:latest
        command: ["celery", "-A", "session-service", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: session-service-config
        - secretRef:
            name: session-service-secrets