apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service-worker
  namespace: speakin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service-worker
  template:
    metadata:
      labels:
        app: session-service-worker
    spec:
      containers:
      - name: session-service-worker
        image: hamrazhakeem/speakin-session-service:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "session_service", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: session-service-config
        - secretRef:
            name: session-service-secrets
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "200m"
        #     memory: "256Mi"