apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-worker
  namespace: speakin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-worker
  template:
    metadata:
      labels:
        app: user-service-worker
    spec:
      containers:
      - name: user-service-worker
        image: hamrazhakeem/speakin-user-service:latest
        command: ["celery", "-A", "user_service", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"