# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_services import payment_service_pb2 as grpc__services_dot_payment__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_services/payment_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LockCredits = channel.unary_unary(
                '/PaymentService/LockCredits',
                request_serializer=grpc__services_dot_payment__service__pb2.LockCreditsRequest.SerializeToString,
                response_deserializer=grpc__services_dot_payment__service__pb2.LockCreditsResponse.FromString,
                _registered_method=True)
        self.RefundLockedCredits = channel.unary_unary(
                '/PaymentService/RefundLockedCredits',
                request_serializer=grpc__services_dot_payment__service__pb2.RefundLockedCreditsRequest.SerializeToString,
                response_deserializer=grpc__services_dot_payment__service__pb2.RefundLockedCreditsResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LockCredits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundLockedCredits(self, request, context):
        """New method for refund
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LockCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.LockCredits,
                    request_deserializer=grpc__services_dot_payment__service__pb2.LockCreditsRequest.FromString,
                    response_serializer=grpc__services_dot_payment__service__pb2.LockCreditsResponse.SerializeToString,
            ),
            'RefundLockedCredits': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundLockedCredits,
                    request_deserializer=grpc__services_dot_payment__service__pb2.RefundLockedCreditsRequest.FromString,
                    response_serializer=grpc__services_dot_payment__service__pb2.RefundLockedCreditsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LockCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/LockCredits',
            grpc__services_dot_payment__service__pb2.LockCreditsRequest.SerializeToString,
            grpc__services_dot_payment__service__pb2.LockCreditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundLockedCredits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/RefundLockedCredits',
            grpc__services_dot_payment__service__pb2.RefundLockedCreditsRequest.SerializeToString,
            grpc__services_dot_payment__service__pb2.RefundLockedCreditsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
