version: '3.8'

services:
  api_gateway:
    container_name: api_gateway
    build:
      context: ./api_gateway
    volumes:
      - ./api_gateway:/app
    ports:
      - "8080:8080" 
    networks:
      - microservice_network

  user_service:
    container_name: user_service
    build:
      context: ./user_service
    volumes:
      - ./user_service:/app
    ports:
      - "8000:8000"
      - "50051:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy
      user_service_db:
        condition: service_started
    networks:
      - microservice_network

  payment_service:
    container_name: payment_service
    build:
      context: ./payment_service
    volumes:
      - ./payment_service:/app
    ports:
      - "8001:8001"
      - "50052:50052"
    depends_on:
      - payment_service_db
    networks:
      - microservice_network

  session_service:
    container_name: session_service
    build:
      context: ./session_service
    volumes:
      - ./session_service:/app
    ports:
      - "8002:8002"
    depends_on:
      - session_service_db
    networks:
      - microservice_network

  message_service:
    container_name: message_service
    build:
      context: ./message_service
    volumes:
      - ./message_service:/app
    ports:
      - "8003:8003"
    depends_on:
      - message_service_db
    networks:
      - microservice_network

  user_service_db:
    image: postgres:13
    container_name: user_service_db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microservice_network
    ports:
      - "5432:5432"

  payment_service_db:
    image: postgres:13
    container_name: payment_service_db
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME}
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - microservice_network
    ports:
      - "5433:5432"

  session_service_db:
    image: postgres:13
    container_name: session_service_db
    environment:
      POSTGRES_DB: ${SESSION_DB_NAME}
      POSTGRES_USER: ${SESSION_DB_USER}
      POSTGRES_PASSWORD: ${SESSION_DB_PASSWORD}
    volumes:
      - session_db_data:/var/lib/postgresql/data
    networks:
      - microservice_network
    ports:
      - "5434:5432"

  message_service_db:
    image: postgres:13
    container_name: message_service_db
    environment:
      POSTGRES_DB: ${MESSAGE_DB_NAME}
      POSTGRES_USER: ${MESSAGE_DB_USER}
      POSTGRES_PASSWORD: ${MESSAGE_DB_PASSWORD}
    volumes:
      - message_db_data:/var/lib/postgresql/data
    networks:
      - microservice_network
    ports:
      - "5435:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservice_network

  stripe_cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    command: listen --forward-to http://host.docker.internal:8080/api/webhook/
    networks:
      - microservice_network
    depends_on:
      - payment_service
    restart: on-failure:5 
    volumes:
      - ./payment_service:/app
    env_file:
      - .env 

  user_service_worker:
    container_name: user_service_worker
    build:
      context: ./user_service
    command: celery -A user_service worker --loglevel=info
    volumes:
      - ./user_service:/app
    depends_on:
      - redis
      - user_service
    networks:
      - microservice_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservice_network

volumes:
  user_db_data:
  payment_db_data:
  session_db_data:
  message_db_data:
  redis_data:
  rabbitmq_data:

networks:
  microservice_network:
    driver: bridge