apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: message-db
  namespace: speakin
spec:
  serviceName: message-db
  replicas: 1
  selector:
    matchLabels:
      app: message-db
  template:
    metadata:
      labels:
        app: message-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: message-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: message-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: message-db
  namespace: speakin
spec:
  selector:
    app: message-db
  ports:
    - port: 5435
      targetPort: 5432
  type: ClusterIP