apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
  namespace: speakin
spec:
  serviceName: payment-db
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: payment-db-secrets
        volumeMounts:
        - name: payment-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: payment-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: speakin
spec:
  selector:
    app: payment-db
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP