name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-cd.yml'
      - 'server/**'
      - '!server/k8s/**'
      - '!server/docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Services
      run: |
        docker buildx build --push --tag hamrazhakeem/speakin-api-gateway:latest ./server/api_gateway
        docker buildx build --push --tag hamrazhakeem/speakin-user-service:latest ./server/user_service
        docker buildx build --push --tag hamrazhakeem/speakin-payment-service:latest ./server/payment_service
        docker buildx build --push --tag hamrazhakeem/speakin-session-service:latest ./server/session_service
        docker buildx build --push --tag hamrazhakeem/speakin-message-service:latest ./server/message_service

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.28.0'

    - name: Update kubeconfig with IAM authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
        aws eks get-token --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} | kubectl apply -f -
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl rollout restart deployment -n speakin
        kubectl rollout status deployment -n speakin

    - name: Verify deployment
      run: |
        kubectl get pods -n speakin
        kubectl get services -n speakin